[procedure]
id = "[PROCEDURE_ID]"
fields = [
    { label = "[LABEL_1]", value = "[VALUE_1]" },
    { label = "[LABEL_2]", value = "[VALUE_2]" },
    { label = "[LABEL_3]", value = "[VALUE_3]" },
]

[openai-whisper]
model = "medium"

[telegram-bot]
enabled = true
chat-id = "[CHAT_ID]"
bot-token = "[BOT_TOKEN]"
