[telegram]
bot_token = "[BOT_TOKEN]"
chat_id = "[CHAT_ID]"

[openai]
whisper_model = "medium"

[procedure]
id = "[PROCEDURE_ID]"
fields = [
    { label = "[LABEL_1]", value = "[VALUE_1]" },
    { label = "[LABEL_2]", value = "[VALUE_2]" },
    { label = "[LABEL_3]", value = "[VALUE_3]" },
]
